"""Command line: sr-schemadoc [--xsd F] [--sch F] [-o DIR] [--check]  (also python -m sr_core.schemadoc).

Run from an sr-core checkout with no arguments, it reads the canonical schema in schema/ (scene-render.xsd and
scene-render.sch; the version is the XSD's own xs:schema/@version, not part of the file name) and writes the
site to docs/schema/. Installed elsewhere, --xsd and -o are required.
"""
from __future__ import annotations

import argparse
import os
import sys

from . import __version__
from .html import build
from .model import SchemaError, read

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MARKER = ".sr-schemadoc"


def in_checkout() -> bool:
    """True when this code runs from an sr-core source tree (not an installed copy)."""
    return (os.path.exists(os.path.join(REPO, "schema", "scene-render.xsd"))
            and os.path.exists(os.path.join(REPO, "pyproject.toml")))


def canonical_schema() -> tuple[str | None, str | None]:
    if not in_checkout():
        return None, None
    xsd = os.path.join(REPO, "schema", "scene-render.xsd")
    sch = xsd[:-4] + ".sch"
    return xsd, sch if os.path.exists(sch) else None


def render(xsd: str, sch: str | None) -> dict[str, bytes]:
    xb = open(xsd, "rb").read()
    sb = open(sch, "rb").read() if sch else None
    s = read(xb, sb, os.path.basename(xsd), os.path.basename(sch) if sch else None)
    files = {k: v.encode("utf-8") for k, v in build(s).items()}
    files[os.path.basename(xsd)] = xb
    if sch:
        files[os.path.basename(sch)] = sb
    files[MARKER] = b"generated by sr-schemadoc; do not edit, regenerate\n"
    return dict(sorted(files.items()))


def existing(out: str) -> dict[str, bytes]:
    found = {}
    for dp, _, fs in os.walk(out):
        for f in fs:
            p = os.path.join(dp, f)
            found[os.path.relpath(p, out).replace(os.sep, "/")] = open(p, "rb").read()
    return found


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="sr-schemadoc", description="Static HTML reference for the scene-render schema.")
    ap.add_argument("--version", action="version", version=f"sr-schemadoc {__version__}")
    ap.add_argument("--xsd", help="XSD to document (default: sr-core's canonical schema)")
    ap.add_argument("--sch", help="Schematron rules (default: the .sch beside the XSD; 'none' to omit)")
    ap.add_argument("-o", "--out", help="output directory (default: sr-core/docs/schema)")
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if the output directory is stale")
    a = ap.parse_args(argv)

    xsd, sch = (a.xsd, None) if a.xsd else canonical_schema()
    if a.xsd and a.sch is None and os.path.exists(a.xsd[:-4] + ".sch"):
        sch = a.xsd[:-4] + ".sch"
    if a.sch:
        sch = None if a.sch == "none" else a.sch
    if not xsd:
        ap.error("not in an sr-core checkout: pass --xsd (and -o)")
    if not a.out and not in_checkout():
        ap.error("not in an sr-core checkout: pass -o")
    out = a.out or os.path.join(REPO, "docs", "schema")
    try:
        files = render(xsd, sch)
    except (SchemaError, OSError) as e:
        print(f"sr-schemadoc: {e}", file=sys.stderr)
        return 2

    have = existing(out) if os.path.isdir(out) else {}
    if a.check:
        stale = sorted(k for k in set(files) | set(have) if files.get(k) != have.get(k))
        if stale:
            print(f"{out}: stale ({len(stale)} files differ, e.g. {', '.join(stale[:5])}); run sr-schemadoc",
                  file=sys.stderr)
            return 1
        print(f"{out}: up to date ({len(files)} files)")
        return 0

    if have and MARKER not in have:
        print(f"sr-schemadoc: {out} exists and was not written by sr-schemadoc; choose another --out",
              file=sys.stderr)
        return 2
    for rel in sorted(set(have) - set(files)):
        os.remove(os.path.join(out, rel))
    changed = 0
    for rel, data in files.items():
        p = os.path.join(out, rel)
        if have.get(rel) == data:
            continue
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "wb") as f:
            f.write(data)
        changed += 1
    for dp, ds, fs in sorted(os.walk(out, topdown=False)):
        if dp != out and not os.listdir(dp):
            os.rmdir(dp)
    print(f"wrote {out}: {len(files)} files, {changed} changed, {len(set(have) - set(files))} removed "
          f"({os.path.basename(xsd)}{', ' + os.path.basename(sch) if sch else ''})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
